#!/bin/bash


# check for root
[[ ${EUID} -ne 0 ]] && echo "::This script must be run as root::" && exit 1

function grpexists {
if [ ! $(getent group $1) ]; then
    echo "group $1 does not exist in master node."
    exit 1
fi
}
function grpexists_slave {
if [ ! $($ACM getent group $1) ]; then
    echo "group $1 does not exist in slave nodes."
    exit 1
fi
}


ACM="arch-chroot /srv/nfsroot"

echo "CLUSTER USER ADD "

if [ ! $($ACM echo "hello") ]; then
	echo "Please make sure no one else is logged into chroot environment(/srv/nfsroot)."
    exit 1
fi


read -p "Enter username [ex: john]: " user_name
read -p "Enter user ID [ex: 2001]: " user_id
read -p "Enter groupname [ex: general]: " group_name

#Checking for special characters
if [[ $group_name == *['!'@#\$%^\&*()_+]* ]]; then
    echo "Group name can't contain special character(!@#$%^&*()_+). Please try again!!"
    exit 1
fi


for i in ${group_name//,/ }
do
    grpexists $i
    grpexists_slave $i
done

read -p "Want to add sudo privillage? (y/n): " su_user

if [ $su_user = "y" ]; then
	useradd -m -u ${user_id} -g users -G sudo,${group_name} -s /usr/bin/zsh ${user_name}
	$ACM useradd -m -u ${user_id} -g users -G sudo,${group_name} -s /usr/bin/zsh ${user_name}
else
	useradd -m -u ${user_id} -g users -G ${group_name} -s /usr/bin/zsh ${user_name}
	$ACM useradd -m -u ${user_id} -g users -G ${group_name} -s /usr/bin/zsh ${user_name}
fi

passwd ${user_name} 
$ACM passwd ${user_name} 

echo "DONE!!"
