#!/bin/bash

# check for root
[[ ${EUID} -ne 0 ]] && echo "::This script must be run as root::" && exit 1


interface=enp2s0

addr=$(ip -o -4 addr list $interface | awk '{print $4}' | cut -d/ -f1)

hnm=$(cat /etc/hosts | grep $addr | awk '{print $2;}')

#echo $hnm

hostnamectl set-hostname $hnm

