#!/bin/sh

## PLEASE RUN THIS SCRIPT TO ADD MASTER, WHEN ONLY THE MASTER NODE IS ON!!!

# check for root
[[ ${EUID} -ne 0 ]] && echo "::This script must be run as root::" && exit 1

echo "Searching for master node......."

ip_search=192.168.0.0

########### Generate ip_match ###############################

A="$(cut -d'.' -f1 <<<"$ip_search")"
B="$(cut -d'.' -f2 <<<"$ip_search")"

ip_match="$A.$B"

################################################################

#################### Grab IP & MAC Adress ######################

ip=$(nmap -sP $ip_search/24 | awk '/Nmap scan report for/{printf $5;}/MAC Address:/{print " "$3;}' | sort | grep $ip_match | head -1 | awk '{print $1;}')


mac=$(nmap -sP $ip_search/24 | awk '/Nmap scan report for/{printf $5;}/MAC Address:/{print " "$3;}' | sort | grep $ip_match | head -1 | awk '{print $2;}')

###############################################################


if [ ! "$mac" ] && [ ! "$ip" ]; then
	echo "No device or master found!"
elif [ ! "$mac" ]; then
	echo "$ip master" >> /etc/hosts
	read -p "Master Found! Add master to machine-file?[y/n]: " master
	if [ "$master" == "y" ]; then
		echo "master" >> /home/nlocluster/node.conf
    fi
fi
