#!/bin/sh

## PLEASE RUN THIS SCRIPT TO ADD MASTER, WHEN ONLY THE MASTER NODE IS ON!!!

# check for root
[[ ${EUID} -ne 0 ]] && echo "::This script must be run as root::" && exit 1

echo "Searching for master node......."

ip_search=192.168.0.0

########### Generate ip_match ###############################

A="$(cut -d'.' -f1 <<<"$ip_search")"
B="$(cut -d'.' -f2 <<<"$ip_search")"

ip_match="$A.$B"

################################################################

#################### Grab IP & MAC Adress ######################

ip=$(nmap -sP $ip_search/24 | awk '/Nmap scan report for/{printf $5;}/MAC Address:/{print " "$3;}' | sort | grep $ip_match | head -1 | awk '{print $1;}')


mac=$(nmap -sP $ip_search/24 | awk '/Nmap scan report for/{printf $5;}/MAC Address:/{print " "$3;}' | sort | grep $ip_match | head -1 | awk '{print $2;}')

###############################################################
function slurm_setup {
	/usr/bin/hname #setting hostname in new node
	SMD=$(slurmd -C) #grubing slurm.conf configuration for new node
	A=$(echo "$SMD" | awk '{print $1;}')
	B=$(echo "$SMD" | awk '{print $2;}')
	C=$(echo "$SMD" | awk '{print $3;}')
	D=$(echo "$SMD" | awk '{print $4;}')
	E=$(echo "$SMD" | awk '{print $5;}')
	F=$(echo "$SMD" | awk '{print $6;}')
	G=$(echo "$SMD" | awk '{print $7;}')
	#echo "A=$A"
	TXT=$(echo "NodeName=$1 NodeAddr=$ip $B $C $D $E $F $G")
	#echo $TXT
	sed -i "/PartitionName=/i$TXT" /etc/slurm/slurm.conf
	sed -i "/PartitionName=/i$TXT" /srv/nfsroot/etc/slurm/slurm.conf
	systemctl restart slurmctld.service
	systemctl restart slurmd.service
	scontrol reconfigure

}



if [ ! "$mac" ] && [ ! "$ip" ]; then
	echo "No device or master found!"
elif [ ! "$mac" ]; then
	read -p "Master Found! Add master?[y/n]: " master
	if [ "$master" == "y" ]; then
        echo "$ip master" >> /etc/hosts
        echo "$ip master" >> /srv/nfsroot/etc/hosts
        slurm_setup master
    fi
fi

echo "DONE!!!"
