#!/bin/bash

function do_lock () {
    lock_grep=$(ps -A | grep i3lock | awk '{print $1}')
    if [[ -z $lock_grep ]]; then
        echo "i3lock"
        /usr/bin/lock
    fi
}

dup_lockaftersleep=$(ps -A | grep "lockaftersleep" | wc -l)

[[ $dup_lockaftersleep -gt 2 ]] && exit

time_var=$(date | awk '{print $4}')
#echo $time_var | sed 's/:/\n/g'
hour=$(echo $time_var | cut -d':' -f1)
min=$(echo $time_var | cut -d':' -f2)
sec=$(echo $time_var | cut -d':' -f3)

while :
do
    sleep 3
    phour=$(echo $hour)
    pmin=$(echo $min)
    psec=$(echo $sec)

    psec=`expr $psec + 0`

    time_var=$(date | awk '{print $4}')
    #echo $time_var | sed 's/:/\n/g'
    hour=$(echo $time_var | cut -d':' -f1)
    min=$(echo $time_var | cut -d':' -f2)
    sec=$(echo $time_var | cut -d':' -f3)

    #if [[ ! $hour = "$phour" ]]; then
    #    do_lock 
    #    continue
    #fi


    usec=`expr $sec - 3`
    if [[ $usec -lt 0 ]]; then
        umin=`expr $min + 1`
        usec=`expr $usec + 60`
    fi
    diff=`expr $usec - $psec`
    [ "$diff" -lt 0 ] && ((diff *= -1))

    echo $psec $usec $diff
    if [[ $diff -lt 2 ]]; then
        echo "MATCH"
    else
        do_lock
        echo "NOT MATCH"
    fi

    done
